### ISSUE TITLE
Difference test failure

### ISSUE THREAD

**Issue by kyleknighted** [xx45/dayjs#111]
Getting the following error while running the test suite.

```
 FAIL  test/display.test.js
  ● Difference › diff -> in seconds, days, weeks, months, quarters, years

    expect(received).toBe(expected) // Object.is equality

    Expected value to be:
      -86403600
    Received:
      -86400000

      131 |     const units = ['seconds', 'days', 'weeks', 'months', 'quarters', 'years']
      132 |     units.forEach((unit) => {
    > 133 |       expect(dayjsA.diff(dayjsB, unit)).toBe(momentA.diff(momentB, unit))
      134 |       expect(dayjsA.diff(dayjsB, unit, true)).toBe(momentA.diff(momentB, unit, true))
      135 |       expect(dayjsA.diff(dayjsC, unit)).toBe(momentA.diff(momentC, unit))
      136 |       expect(dayjsA.diff(dayjsC, unit, true)).toBe(momentA.diff(momentC, unit, true))

      at test/display.test.js:133:41
          at Array.forEach (<anonymous>)
      at Object.<anonymous> (test/display.test.js:132:11)
```

**Comment by iamkun** [comment]
Can not reproduce on my computer or our CI environment.

Any further detail you can supply? Timezone, Daylight Saving Time, ...

**Comment by kyleknighted** [comment]
``` 
± |master ✓| → node -v
v8.11.1

± |master ✓| → npm -v
5.6.0

± |master ✓| → yarn -v
1.6.0
```

Currently in the Eastern timezone USA.  Not sure what the cause is, but it looks like my PR passed the tests still, so it must just be a local environment issue. ¯\_(ツ)_/¯

**Comment by iamkun** [comment]
Allright.
I'll close this issue. If you still have a problem, feel free to re-open it :)
